# Generated by Django 5.1.1 on 2024-10-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('genderf', models.IntegerField()),
                ('genderm', models.IntegerField()),
                ('size', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('pm', models.IntegerField()),
                ('fp', models.IntegerField()),
            ],
        ),
    ]
